export enum AuditTargetType {
	USER = 'user',
	PROPERTY = 'property',
	UNIT = 'unit',
	TENANT = 'tenant',
	INVOICE = 'invoice',
	PAYMENT = 'payment',
	WALLET = 'wallet',
	RECEIPT = 'receipt',
	EXPENSE = 'expense',
	VENDOR = 'vendor',
	MAINTENANCE = 'maintenance',
	NOTIFICATION = 'notification',
	SETTINGS = 'settings',
	ROLE = 'role',
	PERMISSION = 'permission',
	ORGANIZATION = 'organization',
	SUBSCRIPTION = 'subscription',
	PLATFORM_CONFIG = 'platform_config',
	CHECKLIST = 'checklist',
	METER_READING = 'meter_reading',
	RENT_ESCALATION = 'rent_escalation',
	REPORT = 'report',
	STATEMENT = 'statement',
}
