export enum AuditTargetType {
	USER = 'user',
	PROPERTY = 'property',
	UNIT = 'unit',
	TENANT = 'tenant',
	INVOICE = 'invoice',
	PAYMENT = 'payment',
	WALLET = 'wallet',
	RECEIPT = 'receipt',
	EXPENSE = 'expense',
	VENDOR = 'vendor',
	MAINTENANCE = 'maintenance',
	NOTIFICATION = 'notification',
	SETTINGS = 'settings',
	ROLE = 'role',
	PERMISSION = 'permission',
}
