import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigrations1771238413822 implements MigrationInterface {
    name = 'InitialMigrations1771238413822'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."permissions_resource_enum" AS ENUM('users', 'properties', 'units', 'tenants', 'invoices', 'payments', 'wallet', 'expenses', 'vendors', 'maintenance', 'communications', 'reports', 'settings')`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('create', 'read', 'update', 'delete', 'export')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "permission_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" "public"."permissions_resource_enum" NOT NULL, "action" "public"."permissions_action_enum" NOT NULL, "name" character varying NOT NULL, "description" text, CONSTRAINT "PK_1717db2235a5b169822e7f753b1" PRIMARY KEY ("permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "role_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "is_system_role" boolean NOT NULL DEFAULT false, "is_admin_role" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_09f4c8130b54f35925588a37b6a" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid, "email" character varying NOT NULL, "password" character varying, "firstName" character varying, "lastName" character varying, "phone" character varying, "avatar_url" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "phone_verified" boolean NOT NULL DEFAULT false, "email_verified" boolean NOT NULL DEFAULT false, "reset_password_token" character varying, "reset_password_expires" TIMESTAMP, "suspension_reason" text, "last_login_at" TIMESTAMP, "refresh_token" character varying, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('user_created', 'user_updated', 'user_deleted', 'user_suspended', 'user_reactivated', 'user_role_changed', 'property_created', 'property_updated', 'property_deleted', 'unit_created', 'unit_updated', 'tenant_created', 'tenant_updated', 'tenant_vacated', 'invoice_generated', 'invoice_updated', 'invoice_cancelled', 'invoice_auto_settled', 'invoice_partially_settled', 'payment_received', 'payment_failed', 'payment_reversed', 'stk_push_initiated', 'wallet_credited', 'wallet_debited', 'wallet_refunded', 'penalty_applied', 'expense_created', 'expense_updated', 'expense_completed', 'maintenance_requested', 'maintenance_updated', 'maintenance_resolved', 'notification_sent', 'reminder_sent', 'bulk_reminder_sent', 'settings_updated', 'role_created', 'role_updated', 'role_deleted', 'receipt_generated', 'created', 'updated', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_targettype_enum" AS ENUM('user', 'property', 'unit', 'tenant', 'invoice', 'payment', 'wallet', 'receipt', 'expense', 'vendor', 'maintenance', 'notification', 'settings', 'role', 'permission')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "audit_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "performed_by" uuid NOT NULL, "targetType" "public"."audit_logs_targettype_enum" NOT NULL, "target_id" character varying, "details" text NOT NULL, "ip_address" character varying, "metadata" jsonb, CONSTRAINT "PK_6f2dad3880d1d6f9bf560ea91c7" PRIMARY KEY ("audit_id"))`);
        await queryRunner.query(`CREATE TABLE "properties" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "property_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "location" character varying NOT NULL, "address" character varying, "total_units" integer NOT NULL DEFAULT '0', "paybill_number" character varying, "logo_url" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b3fea131924b6a50785b0f4ce6d" PRIMARY KEY ("property_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97a55236e173864fa226a62313" ON "properties" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_53cecaa43eb33fbf9ba9e07141" ON "properties" ("name") `);
        await queryRunner.query(`CREATE TABLE "units" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "unit_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unit_number" character varying NOT NULL, "property_id" uuid NOT NULL, "rent_amount" numeric(10,2) NOT NULL, "is_occupied" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_775085c1f14fcfa208160ace4e5" UNIQUE ("property_id", "unit_number"), CONSTRAINT "PK_5cef2f225de998fb92c007f0cae" PRIMARY KEY ("unit_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f221e6d7bfd686266003b982b5" ON "units" ("property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('active', 'notice_period', 'vacated')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "tenant_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "unit_id" uuid NOT NULL, "wallet_balance" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'active', "lease_start" TIMESTAMP NOT NULL, "lease_end" TIMESTAMP, CONSTRAINT "UQ_0e2bb90ad27fa92910185792aca" UNIQUE ("user_id"), CONSTRAINT "UQ_52037a8ca5a57ca7f7e875d7dff" UNIQUE ("unit_id"), CONSTRAINT "REL_0e2bb90ad27fa92910185792ac" UNIQUE ("user_id"), CONSTRAINT "REL_52037a8ca5a57ca7f7e875d7df" UNIQUE ("unit_id"), CONSTRAINT "PK_2bc5fb666b382723700bb4c1e76" PRIMARY KEY ("tenant_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c59559e7872bc9726adef4669f" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('paid', 'partially_paid', 'unpaid', 'overdue', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "invoice_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying NOT NULL, "tenant_id" uuid NOT NULL, "billing_month" TIMESTAMP NOT NULL, "rent_amount" numeric(10,2) NOT NULL, "water_charge" numeric(10,2) NOT NULL DEFAULT '0', "electricity_charge" numeric(10,2) NOT NULL DEFAULT '0', "other_charges" numeric(10,2) NOT NULL DEFAULT '0', "other_charges_desc" character varying, "subtotal" numeric(10,2) NOT NULL, "penalty_amount" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "amount_paid" numeric(10,2) NOT NULL DEFAULT '0', "balance_due" numeric(10,2) NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'unpaid', "due_date" TIMESTAMP NOT NULL, "paid_at" TIMESTAMP, "penalty_applied_at" TIMESTAMP, "notes" character varying, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_a62eb88a23934fb83945c3e58af" PRIMARY KEY ("invoice_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0457ee681a50419881ea2ee796" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1daca8a2c033a72b3964f3c02" ON "invoices" ("billing_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_440f531f452dcc4389d201b9d4" ON "invoices" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('mpesa_paybill', 'mpesa_stk_push', 'wallet_deduction', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'reversed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "payment_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "invoice_id" uuid, "amount" numeric(10,2) NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "mpesa_receipt_number" character varying, "mpesa_phone_number" character varying, "transaction_date" TIMESTAMP NOT NULL DEFAULT NOW(), CONSTRAINT "UQ_988da860891c1333dba57ad8bbe" UNIQUE ("mpesa_receipt_number"), CONSTRAINT "PK_8866a3cfff96b8e17c2b204aae0" PRIMARY KEY ("payment_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_988da860891c1333dba57ad8bb" ON "payments" ("mpesa_receipt_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9109b53fca5cef7720aca72974" ON "payments" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "receipts" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "receipt_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "receipt_number" character varying NOT NULL, "invoice_id" uuid NOT NULL, "total_paid" numeric(10,2) NOT NULL, "pdf_url" character varying, CONSTRAINT "UQ_f57eed557248913be5ee2316dba" UNIQUE ("receipt_number"), CONSTRAINT "UQ_0dd8f628268da8afb8dbdf3b7cc" UNIQUE ("invoice_id"), CONSTRAINT "REL_0dd8f628268da8afb8dbdf3b7c" UNIQUE ("invoice_id"), CONSTRAINT "PK_8613250be825686eb9bf90189b7" PRIMARY KEY ("receipt_id"))`);
        await queryRunner.query(`CREATE TABLE "system_settings" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "system_setting_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "platform_name" character varying NOT NULL DEFAULT 'RentFlow', "support_email" character varying NOT NULL DEFAULT 'support@rentflow.co.ke', "app_logo" character varying(500), "app_favicon" character varying(500), "contact_phone" character varying(20), "contact_address" text, "max_file_upload_size" integer NOT NULL DEFAULT '10', "allowed_file_types" text, "allow_signup" boolean NOT NULL DEFAULT false, "require_verification" boolean NOT NULL DEFAULT false, "email_notifications" boolean NOT NULL DEFAULT true, "sms_notifications" boolean NOT NULL DEFAULT true, "admin_alerts" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4e817db22a3cc7f4455232ee8ea" PRIMARY KEY ("system_setting_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('credit', 'debit_invoice', 'debit_penalty', 'refund')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "wallet_transaction_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "balance_before" numeric(10,2) NOT NULL, "balance_after" numeric(10,2) NOT NULL, "reference" character varying, "description" character varying, CONSTRAINT "PK_208534ece8101bbffc80106d59f" PRIMARY KEY ("wallet_transaction_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37966f1d64f7c9c64da01f8399" ON "wallet_transactions" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "vendors" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "vendor_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying, "specialty" character varying NOT NULL, "rating" numeric(2,1), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0a594d3003be38ea23c2fce9a3c" PRIMARY KEY ("vendor_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04d426b73aeaf5f59420bee11e" ON "vendors" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ed4798bf7481a83d25f3e1ec9" ON "vendors" ("specialty") `);
        await queryRunner.query(`CREATE INDEX "IDX_83065ec2a2c5052786c122e95b" ON "vendors" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('plumbing', 'roofing', 'electrical', 'painting', 'security', 'general_maintenance', 'structural', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('pending', 'approved', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "expense_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "property_id" uuid NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, "priority" "public"."expenses_priority_enum" NOT NULL DEFAULT 'medium', "description" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "vendor_id" uuid, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'pending', "scheduled_date" TIMESTAMP, "completed_date" TIMESTAMP, "notes" character varying, "photos" text, CONSTRAINT "PK_e05b03cdc63e9849adcebeb0118" PRIMARY KEY ("expense_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c74428bcafedde6850cdacaf0a" ON "expenses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_d45651fdfe08150a636a034319" ON "expenses" ("property_id") `);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_category_enum" AS ENUM('plumbing', 'roofing', 'electrical', 'painting', 'security', 'general_maintenance', 'structural', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_requests_status_enum" AS ENUM('pending', 'approved', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "maintenance_requests" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "maintenance_request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "description" character varying NOT NULL, "category" "public"."maintenance_requests_category_enum" NOT NULL, "priority" "public"."maintenance_requests_priority_enum" NOT NULL DEFAULT 'medium', "photos" text, "status" "public"."maintenance_requests_status_enum" NOT NULL DEFAULT 'pending', "resolved_at" TIMESTAMP, CONSTRAINT "PK_573f8cbf617bdfcc64dd2db3de1" PRIMARY KEY ("maintenance_request_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0330e7473e867931548e20dc4a" ON "maintenance_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_42bdf962a8e2790aaed8379757" ON "maintenance_requests" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('invoice_sent', 'receipt_sent', 'payment_reminder', 'penalty_notice', 'maintenance_update', 'lease_renewal', 'general')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('sms', 'email', 'both')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "notification_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "invoice_id" uuid, "type" "public"."notifications_type_enum" NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "subject" character varying, "message" text NOT NULL, "sent_at" TIMESTAMP, "delivered_at" TIMESTAMP, "fail_reason" character varying, CONSTRAINT "PK_eaedfe19f0f765d26afafa85956" PRIMARY KEY ("notification_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6e4d9d9962720cb5e7ffcaedc" ON "notifications" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d93ddd7e1b890535ecafbb334e" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971" FOREIGN KEY ("performed_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_f221e6d7bfd686266003b982b5f" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_0e2bb90ad27fa92910185792aca" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_52037a8ca5a57ca7f7e875d7dff" FOREIGN KEY ("unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_440f531f452dcc4389d201b9d4b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9109b53fca5cef7720aca72974d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_0dd8f628268da8afb8dbdf3b7cc" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_37966f1d64f7c9c64da01f8399e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_d45651fdfe08150a636a0343192" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_104f4cde0d34dd28e48bedcdf67" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ADD CONSTRAINT "FK_42bdf962a8e2790aaed83797574" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_26a7bfabdb078304e95e489bac8" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_26a7bfabdb078304e95e489bac8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP CONSTRAINT "FK_42bdf962a8e2790aaed83797574"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_104f4cde0d34dd28e48bedcdf67"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_d45651fdfe08150a636a0343192"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_37966f1d64f7c9c64da01f8399e"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_0dd8f628268da8afb8dbdf3b7cc"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9109b53fca5cef7720aca72974d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_440f531f452dcc4389d201b9d4b"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_52037a8ca5a57ca7f7e875d7dff"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_0e2bb90ad27fa92910185792aca"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_f221e6d7bfd686266003b982b5f"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93ddd7e1b890535ecafbb334e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6e4d9d9962720cb5e7ffcaedc"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42bdf962a8e2790aaed8379757"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0330e7473e867931548e20dc4a"`);
        await queryRunner.query(`DROP TABLE "maintenance_requests"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_requests_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d45651fdfe08150a636a034319"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74428bcafedde6850cdacaf0a"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83065ec2a2c5052786c122e95b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ed4798bf7481a83d25f3e1ec9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04d426b73aeaf5f59420bee11e"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37966f1d64f7c9c64da01f8399"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9109b53fca5cef7720aca72974"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_988da860891c1333dba57ad8bb"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_440f531f452dcc4389d201b9d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1daca8a2c033a72b3964f3c02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0457ee681a50419881ea2ee796"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59559e7872bc9726adef4669f"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f221e6d7bfd686266003b982b5"`);
        await queryRunner.query(`DROP TABLE "units"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53cecaa43eb33fbf9ba9e07141"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97a55236e173864fa226a62313"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_targettype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_resource_enum"`);
    }

}
