import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedColumn1771418819175 implements MigrationInterface {
    name = 'AddedColumn1771418819175'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_units_property"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_tenants_user"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_tenants_unit"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_role"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_tenant"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_tenant"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_invoice"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_receipts_invoice"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_wallet_transactions_tenant"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_property"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_vendor"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP CONSTRAINT "FK_maintenance_requests_tenant"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_tenant"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_invoice"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_roles_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_units_property_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tenants_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_due_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_billing_month"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_mpesa_receipt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_invoice_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_transactions_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vendors_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vendors_specialty"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vendors_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_property_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_maintenance_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_maintenance_requests_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_sent_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_permission_id"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "UQ_units_property_unit_number"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ADD COLUMN IF NOT EXISTS "property_id" uuid`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ALTER COLUMN "tenant_id" DROP NOT NULL`);
        await queryRunner.query(`UPDATE "notifications" SET "channel" = 'both' WHERE "channel" IN ('whatsapp', 'all')`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_channel_enum" RENAME TO "notifications_channel_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('sms', 'email', 'both')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notifications_channel_enum" USING "channel"::"text"::"public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_97a55236e173864fa226a62313" ON "properties" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_53cecaa43eb33fbf9ba9e07141" ON "properties" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_f221e6d7bfd686266003b982b5" ON "units" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c59559e7872bc9726adef4669f" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_0457ee681a50419881ea2ee796" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1daca8a2c033a72b3964f3c02" ON "invoices" ("billing_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_440f531f452dcc4389d201b9d4" ON "invoices" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_988da860891c1333dba57ad8bb" ON "payments" ("mpesa_receipt_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9109b53fca5cef7720aca72974" ON "payments" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_37966f1d64f7c9c64da01f8399" ON "wallet_transactions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_04d426b73aeaf5f59420bee11e" ON "vendors" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ed4798bf7481a83d25f3e1ec9" ON "vendors" ("specialty") `);
        await queryRunner.query(`CREATE INDEX "IDX_83065ec2a2c5052786c122e95b" ON "vendors" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_c74428bcafedde6850cdacaf0a" ON "expenses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_d45651fdfe08150a636a034319" ON "expenses" ("property_id") `);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_maintenance_requests_property_id"`);
        await queryRunner.query(`CREATE INDEX "IDX_df11a07b16400e03de99176eb9" ON "maintenance_requests" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0330e7473e867931548e20dc4a" ON "maintenance_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_42bdf962a8e2790aaed8379757" ON "maintenance_requests" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6e4d9d9962720cb5e7ffcaedc" ON "notifications" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_d93ddd7e1b890535ecafbb334e" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "UQ_775085c1f14fcfa208160ace4e5" UNIQUE ("property_id", "unit_number")`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_f221e6d7bfd686266003b982b5f" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_0e2bb90ad27fa92910185792aca" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_52037a8ca5a57ca7f7e875d7dff" FOREIGN KEY ("unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971" FOREIGN KEY ("performed_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_440f531f452dcc4389d201b9d4b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9109b53fca5cef7720aca72974d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_0dd8f628268da8afb8dbdf3b7cc" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_37966f1d64f7c9c64da01f8399e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_d45651fdfe08150a636a0343192" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_104f4cde0d34dd28e48bedcdf67" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ADD CONSTRAINT "FK_42bdf962a8e2790aaed83797574" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP CONSTRAINT IF EXISTS "FK_maintenance_requests_property"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ADD CONSTRAINT "FK_df11a07b16400e03de99176eb9c" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_26a7bfabdb078304e95e489bac8" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_26a7bfabdb078304e95e489bac8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP CONSTRAINT "FK_df11a07b16400e03de99176eb9c"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP CONSTRAINT "FK_42bdf962a8e2790aaed83797574"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_104f4cde0d34dd28e48bedcdf67"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_d45651fdfe08150a636a0343192"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_37966f1d64f7c9c64da01f8399e"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_0dd8f628268da8afb8dbdf3b7cc"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9109b53fca5cef7720aca72974d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_440f531f452dcc4389d201b9d4b"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_ae97aac6d6d471b9d88cea1c971"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_52037a8ca5a57ca7f7e875d7dff"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_0e2bb90ad27fa92910185792aca"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_f221e6d7bfd686266003b982b5f"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "UQ_775085c1f14fcfa208160ace4e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93ddd7e1b890535ecafbb334e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6e4d9d9962720cb5e7ffcaedc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42bdf962a8e2790aaed8379757"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0330e7473e867931548e20dc4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df11a07b16400e03de99176eb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d45651fdfe08150a636a034319"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74428bcafedde6850cdacaf0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83065ec2a2c5052786c122e95b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ed4798bf7481a83d25f3e1ec9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04d426b73aeaf5f59420bee11e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37966f1d64f7c9c64da01f8399"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9109b53fca5cef7720aca72974"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_988da860891c1333dba57ad8bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_440f531f452dcc4389d201b9d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1daca8a2c033a72b3964f3c02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0457ee681a50419881ea2ee796"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59559e7872bc9726adef4669f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f221e6d7bfd686266003b982b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53cecaa43eb33fbf9ba9e07141"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97a55236e173864fa226a62313"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum_old" AS ENUM('sms', 'email', 'both', 'whatsapp', 'all')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notifications_channel_enum_old" USING "channel"::"text"::"public"."notifications_channel_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notifications_channel_enum_old" RENAME TO "notifications_channel_enum"`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ALTER COLUMN "tenant_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" DROP COLUMN "property_id"`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "UQ_units_property_unit_number" UNIQUE ("property_id", "unit_number")`);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_permission_id" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_role_id" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_tenant_id" ON "notifications" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_type" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_sent_at" ON "notifications" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_maintenance_requests_tenant_id" ON "maintenance_requests" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_maintenance_requests_status" ON "maintenance_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_property_id" ON "expenses" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_category" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_status" ON "expenses" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_vendors_name" ON "vendors" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_vendors_specialty" ON "vendors" ("specialty") `);
        await queryRunner.query(`CREATE INDEX "IDX_vendors_is_active" ON "vendors" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_transactions_tenant_id" ON "wallet_transactions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_tenant_id" ON "payments" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_invoice_id" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_mpesa_receipt" ON "payments" ("mpesa_receipt_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_tenant_id" ON "invoices" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_billing_month" ON "invoices" ("billing_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_status" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_due_date" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_tenants_status" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_units_property_id" ON "units" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_name" ON "properties" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_is_active" ON "properties" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_roles_name" ON "roles" ("name") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_requests" ADD CONSTRAINT "FK_maintenance_requests_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_vendor" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("vendor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_property" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_wallet_transactions_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_receipts_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("tenant_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_audit_logs_user" FOREIGN KEY ("performed_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_tenants_unit" FOREIGN KEY ("unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_tenants_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_units_property" FOREIGN KEY ("property_id") REFERENCES "properties"("property_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
